export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'


export const CREATE_PERSON = 'CREATE_PERSON';
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const DELETE_PERSON = 'DELETE_PERSON';
export const CREATE_PERSON_ERROR = 'CREATE_PERSON_ERROR'


export const CREATE_ILLNESS = 'CREATE_ILLNESS';
export const UPDATE_ILLNESS = 'UPDATE_ILLNESS';
export const DELETE_ILLNESS = 'DELETE_ILLNESS'; 
export const CREATE_ILLNESS_ERROR = 'CREATE_ILLNESS_ERROR'